### ISSUE TITLE
Fontawesome icons not load with local json file

### ISSUE THREAD

**Issue by rerraw** [fontIconPicker/fontIconPicker#7]
When I use the ajax URL on your GitHub link it loads all icons without any problem like this
`url: 'https://gist.githubusercontent.com/swashata/c0db916b33700c91ab75f59d4aeba7d3/raw/366789b2d001a99f5f41f1ceab980d991de059c3/fontawesome-icons-with-categories.json',`

I downloaded your json file and I put it within my plugin but in this case not load icons like this
`url: '../wp-content/plugins/Yallanpe-BSN/js/json/fontawesome-icons.json',`

I used this code below do I have an error to load the icons on local json file?

    $.ajax( {
        url: '../wp-content/plugins/Yallanpe-BSN/js/json/fontawesome-icons.json',
        type: 'GET',
        dataType: 'json'
    } )
    .done( function( response ) {
        setTimeout( function() {
            hpemenuFontIconPicker.setIcons( response );
        }, 1000 );
    } );
    var hpemenuFontIconPicker = $('.hpemenu-fonticonpicker').fontIconPicker({
        theme: 'fip-bootstrap'
    });

**Comment by swashata** [comment]
Definitely your URL issue. Use absolute URL with WordPress with [plugins_url](https://developer.wordpress.org/reference/functions/plugins_url/).

Bdw, these questions are best asked on stackoverflow :)

**Comment by rerraw** [comment]
But my code within js file how I can use PHP codes within js file? or must move js code within PHP file the use `plugins_url`?

**Comment by swashata** [comment]
This one looks good enough. https://code.tutsplus.com/tutorials/how-to-pass-php-data-and-strings-to-javascript-in-wordpress--wp-34699

Bdw why do you need another ajax request to load the font definition. You should just inline it within your JavaScript.

Also I noticed the unneeded settimeout in your code. You shouldn't do such things.

Since this question is more a general concept of WordPress APIs and not related to this plugin I suggest your ask in stackoverflow.

**Comment by rerraw** [comment]
Thanks
`wp_localize_script` it is used for .js file not for .json files
I'm moved the your javascript code within `<script></script>` the i used Wordpress php function `plugin_url` now work with me perfectly

**Comment by swashata** [comment]
But still what you are doing is wrong. For starter you can just create a plain object from the json and use inline to avoid ajax call.

If you really need to make an ajax request, then use plugins_url to get the URL, and pass it with wp_localize_script.

Anyway, proceed the way you want. If you ask me I would suggest getting your basic concepts clear by following some great tutorials like freecodecamp.

I will close this issue now, because it is getting off topic.
